apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: https://${TALOS_ORG_NAME}.kubernetes.omni.siderolabs.io
    name: ${TALOS_ORG_NAME}-${TALOS_CLUSTER_NAME}
contexts:
  - context:
      cluster: ${TALOS_ORG_NAME}-${TALOS_CLUSTER_NAME}
      namespace: default
      user: ${TALOS_ORG_NAME}-${TALOS_CLUSTER_NAME}-${TALOS_IDENTITY}
    name: ${TALOS_ORG_NAME}-${TALOS_CLUSTER_NAME}
current-context: ${TALOS_ORG_NAME}-${TALOS_CLUSTER_NAME}
users:
  - name: ${TALOS_ORG_NAME}-${TALOS_CLUSTER_NAME}-${TALOS_IDENTITY}
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=https://${TALOS_ORG_NAME}.omni.siderolabs.io/oidc
          - --oidc-client-id=native
          - --oidc-extra-scope=cluster:${TALOS_CLUSTER_NAME}
        command: kubectl
        env: null
        provideClusterInfo: false
